/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToxinsIndexRouteImport } from './routes/toxins/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ToxinsSlugRouteImport } from './routes/toxins/$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToxinsIndexRoute = ToxinsIndexRouteImport.update({
  id: '/toxins/',
  path: '/toxins/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToxinsSlugRoute = ToxinsSlugRouteImport.update({
  id: '/toxins/$slug',
  path: '/toxins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/toxins/$slug': typeof ToxinsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/toxins/': typeof ToxinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/toxins/$slug': typeof ToxinsSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/toxins': typeof ToxinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/toxins/$slug': typeof ToxinsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/toxins/': typeof ToxinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/ranking'
    | '/search'
    | '/articles/$slug'
    | '/categories/$slug'
    | '/toxins/$slug'
    | '/articles/'
    | '/categories/'
    | '/toxins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/ranking'
    | '/search'
    | '/articles/$slug'
    | '/categories/$slug'
    | '/toxins/$slug'
    | '/articles'
    | '/categories'
    | '/toxins'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/ranking'
    | '/search'
    | '/articles/$slug'
    | '/categories/$slug'
    | '/toxins/$slug'
    | '/articles/'
    | '/categories/'
    | '/toxins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  RankingRoute: typeof RankingRoute
  SearchRoute: typeof SearchRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ToxinsSlugRoute: typeof ToxinsSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ToxinsIndexRoute: typeof ToxinsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toxins/': {
      id: '/toxins/'
      path: '/toxins'
      fullPath: '/toxins/'
      preLoaderRoute: typeof ToxinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toxins/$slug': {
      id: '/toxins/$slug'
      path: '/toxins/$slug'
      fullPath: '/toxins/$slug'
      preLoaderRoute: typeof ToxinsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  RankingRoute: RankingRoute,
  SearchRoute: SearchRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ToxinsSlugRoute: ToxinsSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ToxinsIndexRoute: ToxinsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
